-- To be run at DPLPR
-- Simulate DDL activity at DPLPR
USE [Sales]
GO
ALTER TABLE orders ALTER COLUMN [description] NVARCHAR(1000)
GO
ALTER TABLE orders ALTER COLUMN [description] VARCHAR(500)
GO
ALTER TABLE orders ALTER COLUMN [description] NVARCHAR(1000)
GO
ALTER TABLE orders ALTER COLUMN [description] VARCHAR(500)
GO
ALTER TABLE orders ALTER COLUMN [description] NVARCHAR(500)
GO
ALTER TABLE orders ALTER COLUMN [description] VARCHAR(500)
GO
ALTER TABLE orders ALTER COLUMN [description] NVARCHAR(500)
GO
ALTER TABLE orders ALTER COLUMN [description] NVARCHAR(1000)
GO
ALTER TABLE orders ALTER COLUMN [description] VARCHAR(500)
GO
ALTER TABLE orders ALTER COLUMN [description] NVARCHAR(1000)
GO
ALTER TABLE orders ALTER COLUMN [description] VARCHAR(500)
GO
ALTER TABLE orders ALTER COLUMN [description] NVARCHAR(500)
GO
ALTER TABLE orders ALTER COLUMN [description] VARCHAR(500)
GO
ALTER TABLE orders ALTER COLUMN [description] NVARCHAR(500)
GO
ALTER TABLE orders ALTER COLUMN [description] NVARCHAR(1000)
GO
ALTER TABLE orders ALTER COLUMN [description] VARCHAR(500)
GO
ALTER TABLE orders ALTER COLUMN [description] NVARCHAR(1000)
GO
ALTER TABLE orders ALTER COLUMN [description] VARCHAR(500)
GO
ALTER TABLE orders ALTER COLUMN [description] NVARCHAR(500)
GO
ALTER TABLE orders ALTER COLUMN [description] VARCHAR(500)
GO
ALTER TABLE orders ALTER COLUMN [description] NVARCHAR(500)
GO
ALTER TABLE orders ALTER COLUMN [description] NVARCHAR(1000)
GO
ALTER TABLE orders ALTER COLUMN [description] VARCHAR(500)
GO
ALTER TABLE orders ALTER COLUMN [description] NVARCHAR(1000)
GO
ALTER TABLE orders ALTER COLUMN [description] VARCHAR(500)
GO
ALTER TABLE orders ALTER COLUMN [description] NVARCHAR(500)
GO
ALTER TABLE orders ALTER COLUMN [description] VARCHAR(500)
GO
ALTER TABLE orders ALTER COLUMN [description] NVARCHAR(500)
GO
ALTER TABLE orders ALTER COLUMN [description] NVARCHAR(1000)
GO
ALTER TABLE orders ALTER COLUMN [description] VARCHAR(500)
GO
ALTER TABLE orders ALTER COLUMN [description] NVARCHAR(1000)
GO
ALTER TABLE orders ALTER COLUMN [description] VARCHAR(500)
GO
ALTER TABLE orders ALTER COLUMN [description] NVARCHAR(500)
GO
ALTER TABLE orders ALTER COLUMN [description] VARCHAR(500)
GO
ALTER TABLE orders ALTER COLUMN [description] NVARCHAR(500)
GO
ALTER TABLE orders ALTER COLUMN [description] NVARCHAR(1000)
GO
ALTER TABLE orders ALTER COLUMN [description] VARCHAR(500)
GO
ALTER TABLE orders ALTER COLUMN [description] NVARCHAR(1000)
GO
ALTER TABLE orders ALTER COLUMN [description] VARCHAR(500)
GO
ALTER TABLE orders ALTER COLUMN [description] NVARCHAR(500)
GO
ALTER TABLE orders ALTER COLUMN [description] VARCHAR(500)
GO
ALTER TABLE orders ALTER COLUMN [description] NVARCHAR(500)
GO
ALTER TABLE orders ALTER COLUMN [description] NVARCHAR(1000)
GO
ALTER TABLE orders ALTER COLUMN [description] VARCHAR(500)
GO
ALTER TABLE orders ALTER COLUMN [description] NVARCHAR(1000)
GO
ALTER TABLE orders ALTER COLUMN [description] VARCHAR(500)
GO
ALTER TABLE orders ALTER COLUMN [description] NVARCHAR(500)
GO
ALTER TABLE orders ALTER COLUMN [description] VARCHAR(500)
GO
ALTER TABLE orders ALTER COLUMN [description] NVARCHAR(500)
GO
ALTER TABLE orders ALTER COLUMN [description] NVARCHAR(1000)
GO
ALTER TABLE orders ALTER COLUMN [description] VARCHAR(500)
GO
ALTER TABLE orders ALTER COLUMN [description] NVARCHAR(1000)
GO
ALTER TABLE orders ALTER COLUMN [description] VARCHAR(500)
GO
ALTER TABLE orders ALTER COLUMN [description] NVARCHAR(500)
GO
ALTER TABLE orders ALTER COLUMN [description] VARCHAR(500)
GO
ALTER TABLE orders ALTER COLUMN [description] NVARCHAR(500)